sudo: required
dist: trusty
language: java
jobs:
  include:
    - stage: OAP
      before_install:
      - sudo apt-get install cmake
      - sudo apt-get install libpthread-stubs0-dev
      - sudo apt-get install libnuma-dev

