sudo: required
dist: trusty
language: java
before_install:
- ./install-dependencies.sh
install:
- bash OAP-travis-bootstrap.sh install
before_script:
- bash OAP-travis-bootstrap.sh before_script
script:
- 
- bash OAP-travis-bootstrap.sh script

